ALTER TABLE posts ADD COLUMN IF NOT EXISTS radius_meters INTEGER DEFAULT 800 NOT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS shadowbanned BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS hit_city_wall BOOLEAN DEFAULT FALSE NOT NULL;
